[ubuntu_nodes]
labubuntu ansible_host=192.168.1.101 ansible_user=labadmin ansible_password=secret

[windows_nodes]
friendpc ansible_host=192.168.1.120

[windows_nodes:vars]
ansible_user=labadmin
ansible_password=StrongPassword123
ansible_connection=winrm
ansible_winrm_transport=basic
ansible_winrm_server_cert_validation=ignore

